<?php

declare(strict_types=1);

namespace App\Rules;

use Closure;
use Illuminate\Contracts\Validation\ValidationRule;

/**
 * Accept only storage paths that look like they were produced by this app's
 * own upload pipeline: a relative path under one of the allowed root
 * directories, with a hashed basename and an image extension. Blocks path
 * traversal, absolute paths, dot-only segments, and non-image extensions.
 */
final class SafeStoredUploadPath implements ValidationRule
{
    /**
     * Image extensions produced by the app's upload pipelines.
     *
     * @var array<int, string>
     */
    private const ALLOWED_EXTENSIONS = ['webp', 'jpg', 'jpeg', 'png', 'gif'];

    /**
     * Every top-level folder the app's own upload pipelines write into.
     *
     * @var array<int, string>
     */
    public const APP_UPLOAD_DIRS = [
        'about-us',
        'avatars',
        'gallery',
        'partners',
        'quotes',
        'services',
        'settings',
        'staff',
        'uploads',
        'uploads/blog',
        'uploads/images',
        'uploads/videos',
        'uploads/gallery',
    ];

    /**
     * Root directories that may be adopted as an uploaded file location.
     *
     * @var array<int, string>
     */
    private readonly array $allowedDirs;

    /**
     * @param array<int, string>|null $allowedDirs Root directories that may appear as the first path segment; defaults to {@see self::APP_UPLOAD_DIRS}.
     * @param string|null             $sentinel    Optional exact value that is always accepted (e.g. internal placeholder filename).
     */
    public function __construct(
        ?array $allowedDirs = null,
        private readonly ?string $sentinel = null,
    ) {
        $this->allowedDirs = $allowedDirs ?? self::APP_UPLOAD_DIRS;
    }

    /**
     * Run the validation rule.
     */
    public function validate(string $attribute, mixed $value, Closure $fail): void
    {
        if ($value === null || $value === '') {
            return;
        }

        if (! is_string($value)) {
            $fail('The :attribute must be a string.');

            return;
        }

        if ($this->sentinel !== null && $value === $this->sentinel) {
            return;
        }

        if ($this->isPathTraversal($value)) {
            $fail('The :attribute references an invalid storage path.');

            return;
        }

        $segments = explode('/', $value);

        if (count($segments) < 2) {
            $fail('The :attribute must reference a file stored in an application folder.');

            return;
        }

        if (! in_array($segments[0], $this->allowedDirs, true)) {
            $fail('The :attribute references a storage folder that this application does not manage.');

            return;
        }

        $basename = end($segments);
        $extension = strtolower(pathinfo($basename, PATHINFO_EXTENSION));
        $filename = pathinfo($basename, PATHINFO_FILENAME);

        if (! in_array($extension, self::ALLOWED_EXTENSIONS, true)) {
            $fail('The :attribute must reference an image file.');

            return;
        }

        if (! preg_match('/^[A-Za-z0-9_\-]{1,80}$/', $filename)) {
            $fail('The :attribute must reference a file generated by this application.');
        }
    }

    /**
     * Detect traversal, control characters, and absolute paths.
     */
    private function isPathTraversal(string $value): bool
    {
        if (str_contains($value, "\0") || str_contains($value, '\\')) {
            return true;
        }

        if (str_starts_with($value, '/') || preg_match('/^[A-Za-z]:/', $value) === 1) {
            return true;
        }

        foreach (explode('/', $value) as $segment) {
            if ($segment === '' || $segment === '.' || $segment === '..') {
                return true;
            }
        }

        return false;
    }
}
